[package]
name = "mmviz"
version = "0.1.0"
authors = ["Riku Kanayama (k_kuroguro)"]
license = "MIT"
edition = "2021"
rust-version = "1.65"


[dependencies]
gtk = { version = "0.6.6", package = "gtk4", features = ["v4_8"] }
